# theme.toml template for a Hugo theme

name = "Bigbig"
license = "MIT"
description = "a simple hugo theme"
tags = ["", ""]
min_version = 0.17
categories = ["",""]

[author]
  name = "XIZERO"
  homepage = ""

